steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vera-model-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vera-model-service:latest'
      - '.'
    dir: 'apps/vera-model-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vera-model-service:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vera-model-service:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vera-model-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vera-model-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '8Gi'
      - '--cpu'
      - '4'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'VERA_MODEL_PATH=/app/vera_trained_model'

images:
  - 'gcr.io/$PROJECT_ID/vera-model-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vera-model-service:latest'

timeout: '1200s'
